### PR TITLE
Initial toy setup to debug

### PR DESCRIPTION
**Pull request by dstuck**
Here's the branch I'm currently playing around with to check out postgraphile

### CODE REVIEW

**Comment by tomquisel** [comment]
This is really cool! It's amazing how little code it takes on your end to generate that very thorough GraphQL interface.

Here are my questions / thoughts (probably you're already thinking along these lines since this is just a draft):

* The simplest design might be a scraper script that reads from clinicaltrials.gov, writes directly to the database, and doesn't make use of mutations. That would allow us to expose only a simple query-only GraphQL interface.
* It'd be cool if the GraphQL interface could expose the result of arbitrary GraphQL queries, in addition to what's literally in the database. Is that possible? Like, could you create a query that generates summary statistics per institution, like trial count, and then have postgraphile GraphQL-ify the results of that query? Or do you have to materialize summaries like that into tables (not a big deal either) for postgraphile to pick them up?
* What are you thinking for the most basic report we'd expose? Here's a [simple prototype](https://dazzling-noyce-11a50c.netlify.com/institutions) for the `institutions` view.
* Is there some way to ask postgraphile to reduce the set of features it's implementing to cut down on the complexity of the schema? We probably won't need all the filters & pagination options with our simple use case. No need to do that now, I'm just curious 😄 .

Also, check out the prototype GraphQL schema the frontend is using. It's obviously way too simple (no pagination or anything), but it's roughly a basic schema the frontend and backend could use to interact.

From [here](https://github.com/tomquisel/clinical-trials-report-frontend/blob/master/src/graphql/typeDefs.ts):
```graphql
  type Query {
    institutions: [Institution!]!
  }
  type Institution {
    name: String!
   """number of trials"""
    trials: Int!
   """percent of trials with results reported on time"""
    ontime: Float!
   """percent of trials with results reported late"""
    late: Float!
   """percent of trials with results missing"""
    missing: Float!
  }
```

**Comment by dstuck** [comment]
@tomquisel 
1) As far as the scraper writing directly to the db, that might be simpler, but I'm also interested in attempting to do it the proper gql way first mostly just to get some practice with it. Definitely will reconsider if I get bogged down in it though!

2) Yeah, I'm not sure about gql aggregations; it looks like it's doable but might need to look into it more. One thing that probably makes this easier is that we're just aggregating at the institution level which we can collect a list of trials for simply. Would it be best to get things up and running without aggregations first or is there not really anything valuable on the front end with a list of individual trials?

3) Oh, as far as simplifying the schema, I think it's actually as simple as just cutting it down to just the Types that you want to query. I haven't looked into the schema file myself, but I think you could just truncate it on the frontend!

Sounds like figuring out the aggregation stuff should our next priority since it's gonna be important for enabling the frontend

**Comment by tomquisel** [comment]
Cool! That all makes sense!

For the scraper using the GraphQL interface, you might have an authentication challenge. The queries should all be public, but the mutations need to be private. It might be tricky to enforce that since it's all served off of `/graphql`. You could maybe run two copies of the server, though, one internal and one external to enable it all.

I like the idea of getting an aggregate query up next! The list of trials may be useful if we want to provide a details page, but it's not obvious to me that should be part of the MVP.

Some ideas of aggregations we might want to do to start:
- institution (usually the sponsor)
- the person who is the principal investigator (sometimes the sponsor too)
- maybe by condition?
- maybe by year?

There's also some filtering to figure out, like I'm not sure if we want to limit just to FDA device or drug interventions (the ones that the federal law applies to) or if we want to include other interventions like behavioral. There's probably a whole host of other filtering to do that we haven't encountered yet too 😄.

Of course! Just truncating the schema to what the frontend needs is perfect 😄 .

**Comment by dstuck** [comment]
@tomquisel Ooo! I think we can use computed fields in postgraphile to handle these simple aggregations! I'm gonna merge this in a create a new pr. Hope it's fine leaving the hacky security for now

**Pull request merged**
